
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador.Sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorigual = 21;
  public static final int string = 4;
  public static final int maiorigual = 22;
  public static final int menosmenos = 17;
  public static final int comparacao = 23;
  public static final int abrecha = 11;
  public static final int mais = 14;
  public static final int maiorque = 20;
  public static final int switchh = 9;
  public static final int numero = 5;
  public static final int elsee = 8;
  public static final int fechacha = 12;
  public static final int mult = 15;
  public static final int whilee = 10;
  public static final int menos = 13;
  public static final int inicio = 28;
  public static final int intt = 3;
  public static final int def = 30;
  public static final int div = 16;
  public static final int menorque = 19;
  public static final int EOF = 0;
  public static final int pv = 27;
  public static final int id = 2;
  public static final int abrepar = 24;
  public static final int iff = 7;
  public static final int fechapar = 25;
  public static final int maismais = 18;
  public static final int atr = 26;
  public static final int error = 1;
  public static final int palavra = 6;
  public static final int fim = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "intt",
  "string",
  "numero",
  "palavra",
  "iff",
  "elsee",
  "switchh",
  "whilee",
  "abrecha",
  "fechacha",
  "menos",
  "mais",
  "mult",
  "div",
  "menosmenos",
  "maismais",
  "menorque",
  "maiorque",
  "menorigual",
  "maiorigual",
  "comparacao",
  "abrepar",
  "fechapar",
  "atr",
  "pv",
  "inicio",
  "fim",
  "def"
  };
}

